language: perl
perl:
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    # Dist::Milla requires Perl 5.12, so skip testing 5.10

before_install:
    - sudo apt-get install -y libdist-zilla-perl

install:
    - cpanm -q -n --skip-satisfied Dist::Zilla
    - dzil authordeps --missing | cpanm -n
    - dzil listdeps --missing | cpanm -n

script:
    - dzil smoke --release --author

after_success:
    - cpanm -q -n --skip-satisfied Devel::Cover::Report::Coveralls
    - cpanm -q -n --skip-satisfied Dist::Zilla::App::Command::cover
    - dzil cover -outputdir cover_db -report coveralls
